# Generated by Django 5.2.8 on 2026-04-21 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_cartmodel_cartitemmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
